services:
    auth.provider.externalsite:
        class: darkdiesel\authproviderexternalsite\phpbb\auth\provider\externalsite
        arguments:
            - @dbal.conn
            - @config
            - @passwords.manager
            - @request
            - @user
            - @service_container
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: auth.provider }
    darkdiesel.authproviderexternalsite.listener:
        class: darkdiesel\authproviderexternalsite\event\main_listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
